# This is a basic workflow to help you get started with Actions

name: auto-update-workflow

# Controls when the action will run. 
on:
  schedule:
  - cron: "0 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  auto-update-job:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: configure git
        run: |
          git config --global user.email "nicolas.digregorio@gmail.com"
          git config --global user.name "Nicolas DI GREGORIO"
      - name: run auto-pr.ps1
        run: |
          echo "Install scoop"
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          echo "Install git 7zip and aria2"
          scoop install aria2 7zip git
          echo "Move to shovel"
          scoop config SCOOP_REPO 'https://github.com/Ash258/Scoop-Core'
          scoop update
          Add-MpPreference -ExclusionPath 'C:\Users\runneradmin\scoop'
          Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
          [Environment]::SetEnvironmentVariable('SCOOP', 'C:\Users\runneradmin\scoop', 'User')
          echo "Setting up user agent"
          scoop config aria2-options " --quite=true -U 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36'"
          echo "Install hub, lessmsi, wixtoolset innounp"
          scoop install hub wixtoolset lessmsi innounp
          echo "Enable lessmsi as msi extractor"
          scoop config MSIEXTRACT_USE_LESSMSI $true
          echo "Enable completion"
          New-Item -Path 'C:\Users\runneradmin\Documents\PowerShell\' -ItemType Directory
          Add-Content $PROFILE 'Import-Module ''C:\Users\runneradmin\scoop\apps\scoop\current\supporting\completion\Scoop-Completion.psd1'' -ErrorAction SilentlyContinue'
          echo "Enable shovel command"
          Get-ChildItem 'C:\Users\runneradmin\scoop\shims' -Filter 'scoop.*' | Copy-Item -Destination { Join-Path $_.Directory.FullName (($_.BaseName -replace 'scoop', 'shovel') + $_.Extension) }
          echo "Status scoop"
          scoop status
          echo "Check-in up scoop"
          scoop checkup
          echo "run auto-pr"
          ./bin/auto-pr.ps1 -p
      - name: run autoupdate-winapp2.ps1
        run: |
          echo "run autoupdate-winapp2.ps1"
          .github\scripts\autoupdate-winapp2.ps1 
          git commit -a -m "ccleanerpro: Update winapp2.ini hash"
          git push

