# This is a basic workflow to help you get started with Actions

name: auto-update-workflow

# Controls when the action will run. 
on:
  schedule:
  - cron: "0 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  auto-update-job:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: configure git
        run: |
          git config --global user.email "nicolas.digregorio@gmail.com"
          git config --global user.name "Nicolas DI GREGORIO"
      - name: run auto-pr.ps1
        run: |
          echo "Install scoop"
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          echo "Install hub"
          scoop install hub
          echo "run auto-pr"
          ./bin/auto-pr.ps1 -p
      - name: run autoupdate-winapp2.ps1
        run: |
          echo "run autoupdate-winapp2.ps1"
          .github\scripts\autoupdate-winapp2.ps1 
          git commit -a -m "ccleanerpro: Update winapp2.ini hash"
          git push

