# This is a basic workflow to help you get started with Actions

name: checkver-workflow

# Controls when the action will run. 
on:
  schedule:
  - cron: "0 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkver-job:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Commands
      - name: run checkver.ps1
        run: |
          echo "Install scoop"
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          echo "Install hub"
          scoop install hub
          echo "run auto-pr"
          ./bin/auto-pr.ps1 -r -upstream digrouz/scoop-digrouz
